// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Database Discovery
---
*/
package cmds

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/365admin/magicbox-mongodb/execution"
	"github.com/365admin/magicbox-mongodb/schemas"
	"github.com/365admin/magicbox-mongodb/utils"
)

func DiscoverDiscoverPost(ctx context.Context, args []string) (*schemas.Databaseservices, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "magicbox-mongodb", "05-discover", "10 database discover.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}

	resultingFile := path.Join(utils.WorkDir("magicbox-mongodb"), "databaseservices.json")
	data, err := os.ReadFile(resultingFile)
	if err != nil {
		return nil, err
	}
	resultObject := schemas.Databaseservices{}
	err = json.Unmarshal(data, &resultObject)
	return &resultObject, nil

}
