// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Database Restore
---
*/
package cmds

import (
	"context"

	"github.com/365admin/magicbox-mongodb/execution"
)

func RestoreUnarchivePost(ctx context.Context, args []string) (*string, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "magicbox-mongodb", "30-restore", "40-unarchive.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	return nil, nil

}
