// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Database Restore
---
*/
package cmds

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/365admin/magicbox-mongodb/execution"
	"github.com/365admin/magicbox-mongodb/schemas"
	"github.com/365admin/magicbox-mongodb/utils"
)

func RestoreListtarPost(ctx context.Context, args []string) (*schemas.Backupcontent, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "magicbox-mongodb", "30-restore", "57-listtarfile.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}

	resultingFile := path.Join(utils.WorkDir("magicbox-mongodb"), "backupcontent.json")
	data, err := os.ReadFile(resultingFile)
	if err != nil {
		return nil, err
	}
	resultObject := schemas.Backupcontent{}
	err = json.Unmarshal(data, &resultObject)
	return &resultObject, nil

}
