// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Backup all databases
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/kubernetes-management/execution"
	"github.com/365admin/kubernetes-management/schemas"
	"github.com/365admin/kubernetes-management/utils"
)

func BackupAllPost() usecase.Interactor {
	type Request struct {
		Body schemas.Databaseservices `json:"body" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {
		body, inputErr := json.Marshal(input.Body)
		if inputErr != nil {
			return inputErr
		}

		inputErr = os.WriteFile(path.Join(utils.WorkDir("kubernetes-management"), "databaseservices.json"), body, 0644)
		if inputErr != nil {
			return inputErr
		}

		_, err := execution.ExecutePowerShell("john", "*", "kubernetes-management", "40-backup", "20 backup-all.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Backup all databases")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("40-backup")
	return u
}
