// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Database Restore
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/365admin/magicbox-mongodb/execution"
)

func RestoreUnarchivePost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magicbox-mongodb", "30-restore", "40-unarchive.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Database Restore")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Backup")
	return u
}
